[config]
root_path = "."
# debug | info | warn | error | mute
# Defaults to Info if not provided
log_level = "warn"
# Debounce setting for ignoring reptitive file system notifications
debounce = 1000 # Milliseconds
# Sets what files the watcher should ignore
[config.ignore]
# Directories to ignore
dir = [".git", "node_modules", "frontend", "bin"]
# Files to ignore
file = [".DS_Store", ".gitignore", ".gitkeep"]
# File extensions to watch
watched_extension = ["*.go"]
# Add .gitignore paths to ignore
git_ignore = true

[config.background]
cmd = "wails3 task dev:frontend"

[[config.executes]]
cmd = "go mod tidy"
blocking = true

[[config.executes]]
cmd = "wails3 task build"
blocking = true

[[config.executes]]
cmd = "KILL_STALE"

[[config.executes]]
cmd = "wails3 task run"
primary = true
