site_name: "alpha"
repo_url: https://github.com/wailsapp/wails
edit_uri: edit/v3-alpha/mkdocs-website/docs/
site_url: https://v3alpha.wails.io
site_description: The Wails Project - Build beautiful cross-platform applications using Go
site_author: Lea Anthony
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/wails-logo-horizontal-dark.svg
  icon:
    repo: fontawesome/brands/github
  favicon: /favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant.prefetch
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.prune

    - toc.integrate
    - toc.follow

    - search.suggest
    - search.highlight
    - search.share

    - content.tabs.link
    - content.tabs.annotation
    - content.tabs.copy
    - content.code.copy
    - content.code.annotate
    - content.action.edit
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      restrict_base_path: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - def_list
  - toc:
      permalink: '#'
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - table-reader:
      data_path: "shared"
      allow_missing_files: False
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
#        - locale: cy
#          name: Cymraeg
#          build: true
#          site_description: Y Prosiect Wails - Adeiladu cymwysiadau croesrwyd hardd gan ddefnyddio Go
#          extra:
#            announcement: Mae'r wefan hon wedi'i chyfieithu'n awtomatig. Rhowch wybod i ni os oes unrhyw gamgymeriadau.
#          nav:
#            - Cartref: index.md
#            - Cychwyn:
#                - Gosod: getting-started/installation.md
#                - Eich Cais Cyntaf: getting-started/your-first-app.md
#                - Camau Nesaf: getting-started/next-steps.md
#                - Dysgu Rhagor:
#                    - Runtime: learn/runtime.md
#                - Adborth: getting-started/feedback.md
#            - Adborth: getting-started/feedback.md
#            - Beth sydd Newydd yn v3?: whats-new.md
#            - API:
#                - Cais: API/application.md
#                - Ffenestr: API/window.md
#                - Bar Tasg: API/systray.md
#                - Dewislen: API/menu.md
#                - Prif Linell: API/mainthread.md
#            - Datblygu:
#                - Cyflwyniad: development/introduction.md
#                - Status: development/status.md
#                - Newidiadau v3: development/changes.md
#            - Cynllun Ffordd Ymlaen: roadmap.md
#            - Cofnod Newidiadau: changelog.md
#            - Noddwr❤️: https://github.com/sponsors/leaanthony


extra:
  alternate:
    - name: English
      link: /
      lang: en
#    - name: Cymraeg
#      link: /cy/
#      lang: cy
      
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wailsapp/wails
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wailsapp
    - icon: fontawesome/brands/discord
      link: https://discord.gg/JDdSxwjhGf

  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started/installation.md
    - Your First Application: getting-started/your-first-app.md
    - Next Steps: getting-started/next-steps.md
    - Learn More:
        - Services: learn/services.md
        - Bindings: learn/bindings.md
        - Runtime: learn/runtime.md
        - Build System: learn/build.md
        - Guides:
            - Customising Windows: learn/guides/customising-windows.md
            - File Associations: learn/guides/file-associations.md
    - Feedback: getting-started/feedback.md
  - Feedback: getting-started/feedback.md
  - What's New in v3?: whats-new.md
  - API:
      - Application: API/application.md
      - Window: API/window.md
      - Events: API/events.md
      - System Tray: API/systray.md
      - Menu: API/menu.md
      - Main Thread: API/mainthread.md
  - Development:
    - Introduction: development/introduction.md
    - Status: development/status.md
    - v3 Changes: development/changes.md
  - Status: status.md
  - Change Log: changelog.md
  - Sponsor❤️: https://github.com/sponsors/leaanthony

watch:
  - overrides
  - shared
copyright:
  Copyright © 2024 Lea Anthony
