site_name: "alpha"
site_description: The Wails Project - Build beautiful cross-platform applications using Go
repo_url: https://github.com/wailsapp/wails
edit_uri: edit/v3-alpha/mkdocs-website/docs/
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/wails-logo-horizontal-dark.svg
  icon:
    repo: fontawesome/brands/github
  favicon: /favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.prune

    - toc.integrate
    - toc.follow

    - search.suggest
    - search.highlight
    - search.share

    - content.tabs.link
    - content.tabs.annotation
    - content.tabs.copy
    - content.code.copy
    - content.action.edit
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wailsapp/wails
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wailsapp
    - icon: fontawesome/brands/discord
      link: https://discord.gg/JDdSxwjhGf

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting started:
#    - Introduction: introduction.md
    - Installation: getting-started/installation.md
#    - Creating a Project: getting-started/creating-a-project.md
#    - How does it work: how-does-it-work.md
#    - Developing your Application: getting-started/developing-your-application.md
#    - Compiling your Project: getting-started/compiling-your-project.md
#  - API Reference:
#    - Runtime:
#      - Introduction: reference/runtime/introduction.md
#    - CLI: reference/cli.md
#  - Community:
#    - Template: community/templates.md
#    - Guides:
#      - Angular: guides/angular.md
#    - Showcase:
#      - Emaillit: community/showcase/emailit.md
#    - Contributing: community/contributing.md
#    - Links: community/links.md
    - Next Steps: getting-started/next-steps.md
    - Feedback: getting-started/feedback.md
  - What's New in v3?: whats-new.md
  - API:
      - Application: API/application.md
      - Window: API/window.md
      - System Tray: API/systray.md
      - Menu: API/menu.md
      - Main Thread: API/mainthread.md
  - Development:
    - Introduction: development/introduction.md
    - Status: development/status.md
    - v3 Changes: development/changes.md
  - Change Log: changelog.md
  - Sponsor❤️: https://github.com/sponsors/leaanthony


markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      restrict_base_path: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - admonition
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright:
  Copyright © 2023 Lea Anthony
