name: Generate Sponsor Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-sponsors:
    name: Update Sponsors
    runs-on: ubuntu-latest
    if: github.repository == 'wailsapp/wails'
    steps:
      - uses: actions/checkout@v3

      - name: Set Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Update Sponsors
        run: cd scripts/sponsors && chmod 755 ./generate-sponsor-image.sh && ./generate-sponsor-image.sh
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORS_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: wailsapp

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update sponsors.svg"
          add-paths: "website/static/img/sponsors.svg"
          title: Update Sponsor Image
          body: Generated new image
          branch: update-sponsors
          delete-branch: true
