name: Generate Contributors Image

on:
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
  push:
    branches:
      - master

jobs:
  contributors:
    runs-on: ubuntu-latest
    if: github.repository == 'wailsapp/wails'
    steps:
      - uses: actions/checkout@v3
      - uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: website/static/img/contributors.svg
          avatarSize: 42

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: update contributors.svg"
          add-paths: "website/static/img/contributors.svg"
          title: Update Contributors Image
          body: Generated new image
          branch: chore/update-contributors
          delete-branch: true
