name: Push files to Crowdin

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docs:
    name: Push files to Crowdin
    if: github.repository == 'wailsapp/wails'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v11.1
        id: verify-changed-files
        with:
          files: |
            website/**/*.mdx
            website/**/*.md
            website/**/*.json

      - name: Set node
        if: steps.verify-changed-files.outputs.files_changed != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Push files
        env:
          GITHUB_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        run: |
          cd website
          corepack enable
          pnpm install
          pnpm run crowdin push -b master
